.TH "_imel_point" 3 "Thu Sep 1 2016" "Version 3.0" "Imel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_imel_point \- Rappresentation of a point in Imel library\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Data Fields"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "\fBImelSize\fP \fBx\fP"
.br
.ti -1c
.RI "\fBImelSize\fP \fBy\fP"
.br
.ti -1c
.RI "\fBImelPixel\fP \fBpixel\fP"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
Rappresentation of a point in Imel library\&. 

This type can rappresent a point with coordinates, color and level\&.
.PP
\fBSee also:\fP
.RS 4
\fBimel_point_new\fP 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "\fBImelPixel\fP _imel_point::pixel"
Color and level of the point 
.SS "\fBImelSize\fP _imel_point::x"
Coordinate x 
.SS "\fBImelSize\fP _imel_point::y"
Coordinate y 

.SH "Author"
.PP 
Generated automatically by Doxygen for Imel from the source code\&.
