.TH "_imel_hsl" 3 "Thu Sep 1 2016" "Version 3.0" "Imel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_imel_hsl \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <header\&.h>\fP
.SS "Data Fields"

.PP
.RI "\fB\fP"
.br

.in +1c
.in +1c
.ti -1c
.RI "double \fBh\fP"
.br
.ti -1c
.RI "double \fBs\fP"
.br
.ti -1c
.RI "double \fBl\fP"
.br
.in -1c
.in -1c
.SH "Detailed Description"
.PP 
This type can identify a color through HSL values\&.
.PP
\fBSee also:\fP
.RS 4
\fBimel_pixel_new_from_hsl\fP 
.PP
\fBimel_pixel_get_hsl\fP 
.RE
.PP

.SH "Field Documentation"
.PP 
.SS "double _imel_hsl::h"
Hue value 
.SS "double _imel_hsl::l"
Luminosity value 
.SS "double _imel_hsl::s"
Saturation value 

.SH "Author"
.PP 
Generated automatically by Doxygen for Imel from the source code\&.
