.TH "font.h" 3 "Thu Sep 1 2016" "Version 3.0" "Imel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
font.h \- This file contains the internal Imel font\&.  

.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBimel_font\fP [95][14][7]"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains the internal Imel font\&. 


.PP
\fBAuthor:\fP
.RS 4
Davide Francesco Merico 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "\fBbool\fP imel_font[95][14][7]"
Internal font, each letter is 7 px * 14 px\&. There are all printable digit\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Imel from the source code\&.
