.TH "freetype_export_types.h" 3 "Thu Sep 1 2016" "Version 3.0" "Imel" \" -*- nroff -*-
.ad l
.nh
.SH NAME
freetype_export_types.h \- This file contains macro and type for the FreeType library\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
This file contains macro and type for the FreeType library\&. 


.PP
\fBAuthor:\fP
.RS 4
Davide Francesco Merico 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Imel from the source code\&.
